In [2]:
import numpy as np
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(numbers)

[1 2 3 4 5 6 7 8]


In [6]:
numbers.reshape(1,4,3)

ValueError: cannot reshape array of size 8 into shape (1,4,3)

In [7]:
a = np.random.randn(3,4)
b = np.random.randn(1,4)
c = a+b
print(c)

[[-1.03200393 -0.24979273  0.57013341 -0.30466794]
 [-0.99435678  0.67597678  1.27909142  0.71809056]
 [ 0.66308383  0.53575978  0.59079697 -1.50269734]]


In [8]:
a = np.random.randn(4,3)
b = np.random.randn(1,3)
c = a*b
print(c)

[[ 1.37375347  0.282298    0.85856573]
 [-0.23902163  0.03844834  1.03960521]
 [ 0.99299774  0.63743284  0.2261945 ]
 [ 0.90254962 -0.12568526 -0.04568163]]


In [22]:
x = np.array([[[ 0.67826139,  0.29380381],
                     [ 0.90714982,  0.52835647],
                     [ 0.4215251 ,  0.45017551]],

                   [[ 0.92814219,  0.96677647],
                    [ 0.85304703,  0.52351845],
                    [ 0.19981397,  0.27417313]],

                   [[ 0.60659855,  0.00533165],
                    [ 0.10820313,  0.49978937],
                    [ 0.34144279,  0.94630077]]])

In [23]:
x.shape[0]
x.shape[1]
x.shape[2]

2

In [24]:
v = x.reshape((x.shape[0] * x.shape[1], x.shape[2]))

In [25]:
v

array([[0.67826139, 0.29380381],
       [0.90714982, 0.52835647],
       [0.4215251 , 0.45017551],
       [0.92814219, 0.96677647],
       [0.85304703, 0.52351845],
       [0.19981397, 0.27417313],
       [0.60659855, 0.00533165],
       [0.10820313, 0.49978937],
       [0.34144279, 0.94630077]])

In [36]:
def softmax(x):
    """Calculates the softmax for each row of the input x.

    Your code should work for a row vector and also for matrices of shape (m,n).

    Argument:
    x -- A numpy matrix of shape (m,n)

    Returns:
    s -- A numpy matrix equal to the softmax of x, of shape (m,n)
    """
    
    #(≈ 3 lines of code)
    # Apply exp() element-wise to x. Use np.exp(...).
    # x_exp = ...

    # Create a vector x_sum that sums each row of x_exp. Use np.sum(..., axis = 1, keepdims = True).
    # x_sum = ...
    
    # Compute softmax(x) by dividing x_exp by x_sum. It should automatically use numpy broadcasting.
    # s = ...
    
    # YOUR CODE STARTS HERE
    
    x_exp = np.exp(x)
    x_sum = np.sum(x_exp, axis=1).reshape(2,1)
    print(x_sum)
    s = x_exp/x_sum
    
    
    # YOUR CODE ENDS HERE
    
    return s

In [37]:
t_x = np.array([[9, 2, 5, 0, 0],
                [7, 5, 0, 0 ,0]])
print("softmax(x) = " + str(softmax(t_x)))

[[8260.88614278]
 [1248.04631753]]
softmax(x) = [[9.80897665e-01 8.94462891e-04 1.79657674e-02 1.21052389e-04
  1.21052389e-04]
 [8.78679856e-01 1.18916387e-01 8.01252314e-04 8.01252314e-04
  8.01252314e-04]]


In [5]:
y = np.zeros(50, 4, 4, 3)
y.shape

TypeError: zeros() takes from 1 to 3 positional arguments but 4 were given

In [4]:
y

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [